threadpool:
  core: 15
  max: 30
  queue: 10

datasource:
  url: jdbc:mysql://localhost:3306/search?autoReconnect=true&allowMultiQueries=true&sessionVariables=wait_timeout=600&zeroDateTimeBehavior=convertToNull
  username: root
  password:
  hikari:
    max-lifetime: 1800000  # 30 minutes
    idle-timeout: 600000  # 10 minutes
    connection-timeout: 30000  # 30 seconds
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    jdbc.sqlonly: INFO
    jdbc.sqltiming: INFO

hibernate:
  ddl-auto: update
  show_sql: false
  format_sql: false
  physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl